import { StyleSheet } from 'react-native';
import common from './common';

const styles = StyleSheet.create({
  safeArea: {
    ...common.flex1,
    ...common.whiteBg,
  },
  container: {
    ...common.flex1,
    ...common.whiteBg,
  },
  topBar: {
    ...common.row,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 10,
    ...common.whiteBg,
    borderBottomWidth: 1,
    borderBottomColor: '#f2f2f2',
    zIndex: 10,
    ...common.shadow,
    minHeight: 56,
  },
  topBarSearchActive: {
    backgroundColor: '#f5f5f7',
    borderBottomWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
  },
  logoText: {
    fontSize: 20,
    ...common.bold,
    ...common.textDark,
    flex: 1,
  },
  topIcons: {
    ...common.row,
    alignItems: 'center',
    marginLeft: 12,
  },
  searchBarActive: {
    flex: 1,
    ...common.row,
    alignItems: 'center',
    ...common.whiteBg,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 6,
    marginHorizontal: 0,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  searchInputActive: {
    flex: 1,
    fontSize: 16,
    ...common.textDark,
    paddingVertical: 0,
  },
  banner: {
    margin: 16,
    backgroundColor: '#f7faff',
    position: 'relative',
    overflow: 'hidden',
  },
  bannerTitle: {
    fontSize: 20,
    ...common.bold,
    marginTop: 24,
    marginBottom: 8,
    ...common.textDark,
  },
  bannerDesc: {
    fontSize: 14,
    color: '#555',
    marginBottom: 10,
  },
  bannerImage: {
    width: '100%',
    height: 140,
    marginBottom: 8,
  },
  bannerLabel: {
    position: 'absolute',
    top: 0,
    left: 0,
    margin: 0,
    ...common.textPrimary,
    backgroundColor: '#2196f3',
    borderRadius: 0,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  bannerLabelText: {
    color: '#fff',
    fontSize: 13,
    ...common.bold,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    ...common.bold,
    marginLeft: 16,
    marginBottom: 8,
    ...common.textDark,
  },
  card: {
    width: 180,
    marginLeft: 16,
    marginRight: 4,
    ...common.whiteBg,
    borderRadius: 0,
    overflow: 'hidden',
    ...common.shadow,
    marginBottom: 4,
  },
  cardImage: {
    width: '100%',
    height: 110,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
  },
  cardLabel: {
    position: 'absolute',
    top: 0,
    left: 0,
    margin: 0,
    backgroundColor: '#2196f3',
    borderRadius: 0,
    paddingHorizontal: 8,
    paddingVertical: 2,
    zIndex: 2,
  },
  cardLabelText: {
    color: '#fff',
    fontSize: 13,
    ...common.bold,
  },
  bookmarkBtn: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 2,
    backgroundColor: 'rgba(0,0,0,0.15)',
    borderRadius: 12,
    padding: 2,
  },
  cardInfo: {
    padding: 12,
  },
  cardTitle: {
    fontSize: 15,
    ...common.bold,
    ...common.textDark,
    marginBottom: 2,
  },
  cardDesc: {
    fontSize: 13,
    ...common.textGray,
    marginBottom: 2,
  },
  cardDiscount: {
    ...common.textPrimary,
    ...common.bold,
    fontSize: 14,
    marginRight: 6,
  },
  cardPrice: {
    ...common.textDark,
    ...common.bold,
    fontSize: 15,
  },
  tabBar: {
    ...common.row,
    justifyContent: 'space-around',
    alignItems: 'center',
    height: 60,
    borderTopWidth: 1,
    borderTopColor: '#f2f2f2',
    ...common.whiteBg,
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  tabLabel: {
    fontSize: 12,
    ...common.textDark,
    marginTop: 2,
  },
  profileSection: {
    alignItems: 'center',
    paddingVertical: 32,
    backgroundColor: '#f7faff',
    marginBottom: 24,
  },
  profileAvatar: {
    width: 80,
    height: 80,
    borderRadius: 40,
    marginBottom: 12,
  },
  profileName: {
    fontSize: 20,
    ...common.bold,
    ...common.textDark,
    marginBottom: 4,
  },
  profileEmail: {
    fontSize: 14,
    ...common.textGray,
    marginBottom: 2,
  },
  bookmarkSection: {
    marginHorizontal: 16,
    marginBottom: 24,
  },
  bookmarkCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 16,
    marginBottom: 12,
    ...common.shadow,
  },
  bookmarkTitle: {
    fontSize: 16,
    ...common.bold,
    ...common.textDark,
    marginBottom: 2,
  },
  bookmarkDesc: {
    fontSize: 13,
    ...common.textGray,
  },
});

export default styles; 